- name: Build
  run: |
    cd ${{ steps.pwd.outputs.workspace-folder }}
    rm -rf out
    source build/envsetup.sh
    export ALLOW_MISSING_DEPENDENCIES=true
    lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
    make recoveryimage -j$(nproc)
